export const products = [
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
  {
    name: 'Phone XL',
    price: 799,
    image: new URL('https://www.superplanshet.ru/images/Rakuten_BIG_14.jpg'),
    description: 'A large phone with one of the best screens',
  },
  {
    name: 'Phone Mini',
    price: 699,
    image: new URL('https://ae01.alicdn.com/kf/H68babdfeddac4cd3b9ba70281c56b221N.jpg'),
    description: 'A great phone with one of the best cameras',
  },
  {
    name: 'Phone Standard',
    price: 299,
    image: new URL('https://www.technodom.kz/media/catalog/product/b/1/b1ec276a686a7eb87725d3eff0eb238f428fb1b5_230568_1.jpg'),
    description: 'A nice phone with one of the best CP',
  },
];
